### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by zamcham** [zamcham/Ruby-Group-Capstone#30]
We have created a Kanban board for our Ruby Capstone project, we have added all the tasks and properly labeled by Group, and Team member in charge.

The link to our board: https://github.com/zamcham/Ruby-Group-Capstone/projects/1

**Comment by oovillagran** [comment]
We are three members in our team:
- @zamcham *Team Member#1*
- @oovillagran *Team Member#2*
- @naanmohammed *Team Member#3*

**Comment by muneebulrehman** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Descriptive PR
- All tasks accounted for
- All tasks are tagged
- Fair distribution of tasks.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
